language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.1
          env: SYMFONY_DEPRECATIONS_HELPER=strict COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: SYMFONY_VERSION=3.4.*
        - php: 7.3
          env: SYMFONY_VERSION=4.2.* SYMFONY_DEPRECATIONS_HELPER=strict 
    allow_failures:
        - php: 7.4
        - php: nightly

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS --no-interaction
